[phases.setup]
nixPkgs = [
  "nodejs_20",
]

[phases.build]
cmds = [
  # Copy prisma schema from parent directory (when available in build context)
  # If parent dir isn't available, we'll need to handle it differently
  "if [ -d ../prisma ]; then cp -r ../prisma ./prisma-parent || true; fi",
]

[phases.install]
cmds = [
  # Install worker dependencies (includes Prisma in devDependencies)
  "npm install",
  # Generate Prisma client
  # Try to use prisma from parent if available, otherwise use local
  "if [ -d ./prisma-parent ]; then npx prisma generate --schema=./prisma-parent/schema.prisma || npx prisma generate; else npx prisma generate --schema=../prisma/schema.prisma || echo 'Prisma schema not found - make sure to configure Root Directory correctly'; fi",
]

[start]
cmd = "npm run start"
