[phases.setup]
nixPkgs = [
  "nodejs_20",
]

[phases.install]
cmds = [
  # When base directory is /, we can access ../prisma from worker directory
  # Install worker dependencies (includes Prisma in devDependencies)
  # Note: Custom install command in Coolify will run: cd worker && npm install
  "npm install",
]

[phases.build]
cmds = [
  # Generate Prisma client - schema is at ../prisma/schema.prisma from worker directory
  # This runs after install phase, and custom commands handle install/start
  "npx prisma generate --schema=../prisma/schema.prisma",
]
